steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kidconnect-be735/kidconnect-insightface', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kidconnect-be735/kidconnect-insightface']
images:
  - 'gcr.io/kidconnect-be735/kidconnect-insightface'